calibration_info:
  date: '2026-01-23T00:18:15'
  num_images: 10
  reprojection_error: 3.41176097968373
  image_width: 640
  image_height: 480

camera_matrix:
  rows: 3
  cols: 3
  data: [417.07667682972493, 0.0, 318.2682993473888,
         0.0, 417.00031882059596, 275.2724765510972,
         0.0, 0.0, 1.0]

distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.46369159954914274, 0.2830553091289749, -0.012138414250328028, 0.011301088508651214, -0.13498415789423088]
