calibration_date: '2026-02-03T15:50:06.977142'
calibration_method: charuco
camera_matrix:
- - 458.1832217412809
  - 0.0
  - 323.35360711652453
- - 0.0
  - 458.35463530093995
  - 243.95217215301648
- - 0.0
  - 0.0
  - 1.0
charuco_board_size:
- 7
- 5
distortion_coefficients:
- -0.42661564695437004
- 0.17876983807025426
- 0.0009617969941847241
- -0.0001034293509199356
- 0.11252997434166294
image_height: 480
image_width: 640
marker_size_mm: 30.0
num_images: 13
reprojection_error: 0.14220141015691062
square_size_mm: 40.0
